dist: xenial
os: linux
language: generic

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh # this is for api deploy

script:
  - bash deploy.sh

branches:
  only:
    - master

notifications:
  webhooks: https://www.travisbuddy.com